services:
  - type: web
    name: ocr-translation-server
    env: python
    runtime: python
    pythonVersion: "3.10.13"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
    plan: free
    autoDeploy: true